<?php 
require_once "./templates/header.phtml";

foreach($categoria as $categorias): ?>
<table class="table">
  <thead>
    <tr>
    <th scope='col'>material</th>
    <th scope='col'>color</th>
    </tr>
  </thead>
  <tbody>  
    <tr>
    <td><?=$categorias->material ?></td>
    <td><?=$categorias->color ?></td>
    <td ><a class="btn btn-secondary mt-0" href='detalle/<?=$categorias->material?>' type='button'>Detalle</a></td>
    <?php if (isset($_SESSION['USER_ID'])) : ?>
    <td ><a class="btn btn-danger mt-0" href='deleteCategoria/<?=$categorias->id_categoria?>' type='button'>Eliminar</a></td>
      <td ><a class="btn btn-success mt-0"   href='formEditCategoria/<?=$categorias->id_categoria ?>' type='button'>Editar</a></td>
      <?php endif ?>
    </tr>

  
<?php endforeach?>
    
  </tbody>
</table>

   <?php

require_once './templates/footer.phtml';
?>