<?php
require_once './templates/header.phtml';
?>
<h5>Editar categorias</h5>

<form action="formEditCategoria/<?=$id_categoria?>" method="POST" class="form">
    <label>material</label>
        <input type="text"  name="material" class="form-control" placeholder= <?= $categorias->material ?>>
    <label>color</label>
        <input type="text"  name="color" class="form-control" placeholder= <?= $categorias->color ?>>
    <div class="mt-4">
    <button type="submit" class="btn btn-primary mt-2">Editar</a>
    </div>
</form>
<?php
require_once './templates/footer.phtml';
 ?>
