<?php 
require_once 'templates/header.phtml';
?>


<p>Agregar item:</p>
<form action="agregar" method="POST" class="my-4">
    <div class="row">
 
        <div class="col-9">
            <div class="form-group">
                <label>id compra</label>
                <input required name="id_compra" type="number" class="form-control">
            </div>
            
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>talle</label>
                <input required name="talle" type="text" class="form-control">
            </div>
            
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>hora</label>
                <input required name="hora" type="date" class="form-control">
            </div>
            
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>vendedor</label>
                <input required name="vendedor" type="text" class="form-control">
             </div>
            
          </div>

          <div class="col-3">
              <div class="form-group">
                <label>Categoria</label>
                <select required name="Categoria" class="form-control">
                    <option value="buzo">buzo</option>
                    <option value="remera">remera</option>
                    <option value="zapatilla">zapatilla</option>
                    <option value="pantalon">pantalon</option>
                </select>
              </div>
              
           </div>
      
         </div>
       

         <button type="submit" class="btn btn-primary mt-2">Guardar</button>
             <button type="submit" class="btn btn-primary mt-2">eliminar</button>
            <button type="submit" class="btn btn-primary mt-2">editar</button>
    </div>
</form>


<form action="agregar" method="POST" class="my-4">
    <p>Agregar categoria:</p>
    <div class="col-9">
            <div class="form-group">
                <label>prenda_id</label>
                <input required name="prenda_id" type="text" class="form-control">
            </div>
            
        </div>
    <div class="col-9">
            <div class="form-group">
                <label>producto</label>
                <input required name="producto" type="text" class="form-control">
            </div>
            
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>tela</label>
                <input required name="tela" type="text" class="form-control">
            </div>
            <div class="col-9">
            <div class="form-group">
                <label>color</label>
                <input required name="color" type="text" class="form-control">
            </div>
           <button type="submit" class="btn btn-primary mt-2">Guardar</button>
           <button type="submit" class="btn btn-primary mt-2">eliminar</button>
           <button type="submit" class="btn btn-primary mt-2">editar</button>

     </div>
</div>
</form>