<?php 
require_once './templates/header.phtml';
//if ($logged) : ?>
    <form class="form" action="add" method="POST">
    <div class="mb-3">
    <label class="form-label">id_categoria</label>
    <input type="text" name="id_categoria" class="form-control">
    </div>
    <div class="mb-3">
    <label class="form-label">nombre</label>
    <input type="text" name="nombre" class="form-control">
    </div>
    <div class="mb-3">
    <label class="form-label">talle</label>
    <input type="text" name="talle" class="form-control">
    </div>
    <div class="mb-3">
    <label class="form-label" >precio</label>
    <input type="text" name="precio" class="form-control">
    </div>
    <div class="mb-3">
    <label class="form-label">vendedor</label>
    <input type="text" name="vendedor" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary mt-3">Insertar</button>
    </form>
<?
require_once './templates/footer.phtml';
?>