<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Nikes  -indumentaria-</title>



</head>
<body>
    <header>
    <p>
        <a href="home" class="link-info link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">HOME</a>
    </p>
    <p>
        <a href="login" class="link-warning link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">LOGIN</a>
    </p>


    </header>
</body>