<?php
require_once 'templates/header.phtml';
$admin = password_hash($password, PASSWORD_DEFAULT);

?>
<div class="mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <div class="form-group">
            <label for="text">User</label>
            <input type="text" required class="form-control" id=""  aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required class="form-control" id="" name="password">
        </div>

   
       
        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>


