<?php
require_once './templates/header.phtml' ;  
?>
  
    <?php foreach($productos as $producto):?>
      <table class="table">
  <thead>
    <tr>
    <th scope='col'>id_categoria</th>
      <th scope='col'>nombre</th>
      <th scope='col'>talle</th>
      <th scope='col'>precio</th>
      <th scope='col'>vendedor</th>
      <th scope='col'>categoria</th>
    </tr>
  </thead>
  <tbody>  
    <tr>
      <td><?=$producto->id_categoria?></td>
      <td><?=$producto->nombre?></td>
      <td><?=$producto->talle?></td>
      <td><?=$producto->precio?></td>
      <td><?=$producto->vendedor?></td>
      <td><?=$producto->material?></td>
      <td ><a class="btn btn-secondary mt-0" href='productos/detalle/<?=$producto->nombre?>' type='button'>Detalle</a></td>
      <?php if (isset($_SESSION['USER_ID'])) : ?>
       <td ><a class="btn btn-danger mt-0" href='productos/delete/<?=$producto->$id?>' type='button'>Eliminar</a></td>
      <td ><a class="btn btn-success mt-0"   href='formEdit/<?=$producto->nombre?>' type='button'>Editar</a></td>
    <?php endif ?>
    
      </tr>
<?php endforeach ?>
    </tbody>
  </table>
<?php
require_once './templates/footer.phtml';
 ?>