<?php
    require_once 'templates/header.phtml';
    ?>
    <ul>
        <?php foreach ($products as $product): ?>
        <li> <?= $product->prenda_id ?></li>
        <li> <?= $product->id_compra ?></li>
        <li> <?= $product->talle ?></li>
        <li> <?= $product->hora ?></li>
        <li> <?= $product->vendedor ?></li>

    <br>    
        <?php endforeach; ?>
    </ul>
    
          <ul>
            <?php foreach ($categorias as $categoria): ?>
                <li> <?= $categoria->prenda_id ?></li>
                <li> <?= $categoria->producto ?></li>
                <li> <?= $categoria->tela ?></li>
                <li> <?= $categoria->color ?></li>
            <br>
              <?php endforeach; ?>
          </ul>
</body>

</html>